name: HelloPlugin
main: com.srgeppi.main.Main
version: ${version}
api-version: '1.21'
author: srgeppi
description: Minecraft plugin with database integration
commands:
  ping:
    description: Check your ping
    usage: /ping
  info:
    description: View your player information
    usage: /info
  connect:
    description: Link your Minecraft account to website account
    usage: /connect <token>
